In [37]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "mysql+pymysql://analyst:analysis123@localhost:3307/weather_traffic_db"
)

df = pd.read_sql(
    "SELECT * FROM weather_traffic_data",
    con=engine
)

print(df.head())
print(df.shape)

        time  temperature_2m  rain  snowfall  weather_code       date  hour  \
0 2024-01-06            -3.2   0.0       0.0             2 2024-01-06     0
1 2024-01-06            -3.2   0.0       0.0             2 2024-01-06     0
2 2024-01-06            -3.2   0.0       0.0             2 2024-01-06     0
3 2024-01-06            -3.2   0.0       0.0             2 2024-01-06     0
4 2024-01-06            -3.2   0.0       0.0             2 2024-01-06     0

     borough               street direction  avg_vehicle_volume  \
0   Brooklyn  METROPOLITAN AVENUE        WB               14.50
1  Manhattan             9 AVENUE        SB                2.75
2     Queens             BROADWAY        NB               32.50
3     Queens             BROADWAY        SB               49.00
4     Queens         GRAND AVENUE        EB                3.50

   normal_volume  traffic_index  traffic_index_capped
0      11.527778       1.257831              1.257831
1       5.178571       0.531034              0.531034
2      32.527778       0.999146              0.999146
3      41.694444       1.175217              1.175217
4      16.527778       0.211765              0.211765
(23665, 14)

In [38]:
# Parse timestamp
df["timestamp"] = pd.to_datetime(df["date"]) + pd.to_timedelta(df["hour"], unit="h")

KEEP = [
    "timestamp",
    "borough",
    "street",
    "direction",
    "temperature_2m",
    "rain",
    "snowfall",
    "weather_code",
    "avg_vehicle_volume",
    "traffic_index",
    "traffic_index_capped"
]

df = df[KEEP]

# Rename for clarity and consistency
df = df.rename(columns={
    "temperature_2m": "temperature",
    "avg_vehicle_volume": "traffic_volume"
})

# Check and drop rows where critical fields are null
print("Null counts:\n", df.isnull().sum())

df = df.dropna(
    subset=[
        "timestamp",
        "traffic_volume",
        "temperature",
        "rain",
        "snowfall",
        "traffic_index_capped"
    ]
)

print(f"\nClean shape: {df.shape}")
df.head()

Null counts:
 timestamp               0
borough                 0
street                  0
direction               0
temperature             0
rain                    0
snowfall                0
weather_code            0
traffic_volume          0
traffic_index           0
traffic_index_capped    0
dtype: int64

Clean shape: (23665, 11)

,timestamp,borough,street,direction,temperature,rain,snowfall,weather_code,traffic_volume,traffic_index,traffic_index_capped
0,2024-01-06,Brooklyn,METROPOLITAN AVENUE,WB,-3.2,0.0,0.0,2,14.50,1.257831,1.257831
1,2024-01-06,Manhattan,9 AVENUE,SB,-3.2,0.0,0.0,2,2.75,0.531034,0.531034
2,2024-01-06,Queens,BROADWAY,NB,-3.2,0.0,0.0,2,32.50,0.999146,0.999146
3,2024-01-06,Queens,BROADWAY,SB,-3.2,0.0,0.0,2,49.00,1.175217,1.175217
4,2024-01-06,Queens,GRAND AVENUE,EB,-3.2,0.0,0.0,2,3.50,0.211765,0.211765

In [39]:
# Rush hour flag, AM rush: 7-9, PM rush: 16-19
df['hour'] = df['timestamp'].dt.hour

df['rush_hour'] = df['hour'].apply(
    lambda h: 1 if (7 <= h <= 9) or (16 <= h <= 19) else 0
)

# Heavy rain flag
df['heavy_rain'] = (df['rain'] > 0.30).astype(int)

# Temperature ranges
def classify_temp(temp):
    if temp <= 0:
        return 'freezing'
    elif temp <= 7:
        return 'cold'
    elif temp <= 16:
        return 'cool'
    elif temp <= 24:
        return 'comfortable'
    else:
        return 'hot'

df['temp_range'] = df['temperature'].apply(classify_temp)

# Any precipitation flag
df['any_precipitation'] = (
    (df['rain'] > 0) | 
    (df['snowfall'] > 0)
).astype(int)

# Road ID
df['road_id'] = df['street'] + '_' + df['direction']


# weekday and weekend flags

df['day_of_week'] = df['timestamp'].dt.day_name()

df['is_weekend'] = (
    df['timestamp'].dt.dayofweek >= 5
).astype(int)


# Wweather code labels

def weather_label(code):

    if code == 0:
        return "Clear"

    elif code in [1, 2, 3]:
        return "Cloudy"

    elif code in [51, 53, 55]:
        return "Drizzle"

    elif code in [61, 63, 65]:
        return "Rain"

    elif code in [71, 73, 75]:
        return "Snow"

    elif code >= 95:
        return "Storm"

    else:
        return "Other"

df['weather_label'] = df['weather_code'].apply(weather_label)


print("New columns added:")

print(df[
    [
        'timestamp',
        'rush_hour',
        'heavy_rain',
        'temp_range',
        'any_precipitation',
        'road_id',
        'day_of_week',
        'is_weekend',
        'weather_label'
    ]
].head(10))

New columns added:
            timestamp  rush_hour  heavy_rain temp_range  any_precipitation  \
0 2024-01-06 00:00:00          0           0   freezing                  0
1 2024-01-06 00:00:00          0           0   freezing                  0
2 2024-01-06 00:00:00          0           0   freezing                  0
3 2024-01-06 00:00:00          0           0   freezing                  0
4 2024-01-06 00:00:00          0           0   freezing                  0
5 2024-01-06 01:00:00          0           0   freezing                  0
6 2024-01-06 01:00:00          0           0   freezing                  0
7 2024-01-06 01:00:00          0           0   freezing                  0
8 2024-01-06 01:00:00          0           0   freezing                  0
9 2024-01-06 01:00:00          0           0   freezing                  0

                  road_id day_of_week  is_weekend weather_label
0  METROPOLITAN AVENUE_WB    Saturday           1        Cloudy
1             9 AVENUE_SB    Saturday           1        Cloudy
2             BROADWAY_NB    Saturday           1        Cloudy
3             BROADWAY_SB    Saturday           1        Cloudy
4         GRAND AVENUE_EB    Saturday           1        Cloudy
5  METROPOLITAN AVENUE_WB    Saturday           1         Clear
6             9 AVENUE_SB    Saturday           1         Clear
7             BROADWAY_NB    Saturday           1         Clear
8             BROADWAY_SB    Saturday           1         Clear
9         GRAND AVENUE_EB    Saturday           1         Clear

In [40]:
# Group by same street + direction + hourly + borough
grouped_road = df.groupby(
    [
        'timestamp',
        'borough',
        'road_id',
        'street',
        'direction',
        'rush_hour',
        'heavy_rain',
        'temp_range',
        'any_precipitation',
        'hour'
    ]
).agg(
    traffic_volume=('traffic_volume', 'sum'),
    traffic_index=('traffic_index', 'mean'),
    traffic_index_capped=('traffic_index_capped', 'mean'),
    temperature=('temperature', 'mean'),
    rain=('rain', 'mean'),
    snowfall=('snowfall', 'mean'),
    weather_code=('weather_code', 'first')
).reset_index()

print("Road-level grouped shape:", grouped_road.shape)
grouped_road.head()

Road-level grouped shape: (23665, 17)

,timestamp,borough,road_id,street,direction,rush_hour,heavy_rain,temp_range,any_precipitation,hour,traffic_volume,traffic_index,traffic_index_capped,temperature,rain,snowfall,weather_code
0,2024-01-06,Brooklyn,METROPOLITAN AVENUE_WB,METROPOLITAN AVENUE,WB,0,0,freezing,0,0,14.50,1.257831,1.257831,-3.2,0.0,0.0,2
1,2024-01-06,Manhattan,9 AVENUE_SB,9 AVENUE,SB,0,0,freezing,0,0,2.75,0.531034,0.531034,-3.2,0.0,0.0,2
2,2024-01-06,Queens,BROADWAY_NB,BROADWAY,NB,0,0,freezing,0,0,32.50,0.999146,0.999146,-3.2,0.0,0.0,2
3,2024-01-06,Queens,BROADWAY_SB,BROADWAY,SB,0,0,freezing,0,0,49.00,1.175217,1.175217,-3.2,0.0,0.0,2
4,2024-01-06,Queens,GRAND AVENUE_EB,GRAND AVENUE,EB,0,0,freezing,0,0,3.50,0.211765,0.211765,-3.2,0.0,0.0,2

In [41]:
# Borough + hour grouping, one row per borough per hour
grouped_borough = df.groupby(
    [
        'timestamp',
        'borough',
        'hour',
        'rush_hour',
        'heavy_rain',
        'temp_range',
        'any_precipitation'
    ]
).agg(
    traffic_volume=('traffic_volume', 'sum'),
    traffic_index=('traffic_index', 'mean'),
    traffic_index_capped=('traffic_index_capped', 'mean'),
    temperature=('temperature', 'mean'),
    rain=('rain', 'mean'),
    snowfall=('snowfall', 'mean')
).reset_index()

print("Borough-level grouped shape:", grouped_borough.shape)
grouped_borough.head()

Borough-level grouped shape: (9414, 13)

,timestamp,borough,hour,rush_hour,heavy_rain,temp_range,any_precipitation,traffic_volume,traffic_index,traffic_index_capped,temperature,rain,snowfall
0,2024-01-06 00:00:00,Brooklyn,0,0,0,freezing,0,14.50,1.257831,1.257831,-3.2,0.0,0.0
1,2024-01-06 00:00:00,Manhattan,0,0,0,freezing,0,2.75,0.531034,0.531034,-3.2,0.0,0.0
2,2024-01-06 00:00:00,Queens,0,0,0,freezing,0,85.00,0.795376,0.795376,-3.2,0.0,0.0
3,2024-01-06 01:00:00,Brooklyn,1,0,0,freezing,0,8.75,0.915698,0.915698,-4.1,0.0,0.0
4,2024-01-06 01:00:00,Manhattan,1,0,0,freezing,0,2.25,0.887324,0.887324,-4.1,0.0,0.0

In [42]:
# Borough + hour grouping, one row per borough per hour
grouped_borough = df.groupby(
    [
        'timestamp',
        'borough',
        'hour',
        'rush_hour',
        'heavy_rain',
        'temp_range',
        'any_precipitation'
    ]
).agg(
    traffic_volume=('traffic_volume', 'sum'),
    traffic_index=('traffic_index', 'mean'),
    traffic_index_capped=('traffic_index_capped', 'mean'),
    temperature=('temperature', 'mean'),
    rain=('rain', 'mean'),
    snowfall=('snowfall', 'mean')
).reset_index()

print("Borough-level grouped shape:", grouped_borough.shape)
grouped_borough.head()

Borough-level grouped shape: (9414, 13)

,timestamp,borough,hour,rush_hour,heavy_rain,temp_range,any_precipitation,traffic_volume,traffic_index,traffic_index_capped,temperature,rain,snowfall
0,2024-01-06 00:00:00,Brooklyn,0,0,0,freezing,0,14.50,1.257831,1.257831,-3.2,0.0,0.0
1,2024-01-06 00:00:00,Manhattan,0,0,0,freezing,0,2.75,0.531034,0.531034,-3.2,0.0,0.0
2,2024-01-06 00:00:00,Queens,0,0,0,freezing,0,85.00,0.795376,0.795376,-3.2,0.0,0.0
3,2024-01-06 01:00:00,Brooklyn,1,0,0,freezing,0,8.75,0.915698,0.915698,-4.1,0.0,0.0
4,2024-01-06 01:00:00,Manhattan,1,0,0,freezing,0,2.25,0.887324,0.887324,-4.1,0.0,0.0

In [43]:
# Validation checks
print("Null counts (road-level):")
print(teammate_road_df.isnull().sum())

print("\nBorough distribution:")
print(teammate_road_df['borough'].value_counts())

print("\nRush hour distribution:")
print(teammate_road_df['rush_hour'].value_counts())

print("\nTemp range distribution:")
print(teammate_road_df['temp_range'].value_counts())

print("\nHeavy rain distribution:")
print(teammate_road_df['heavy_rain'].value_counts())

print("\nTraffic volume stats:")
print(teammate_road_df['traffic_volume'].describe())

print("\nDate range covered:")
print(f"  From: {teammate_road_df['timestamp'].min()}")
print(f"  To:   {teammate_road_df['timestamp'].max()}")

Null counts (road-level):
timestamp               0
rain                    0
temperature             0
snowfall                0
traffic_volume          0
traffic_index           0
traffic_index_capped    0
road_id                 0
borough                 0
rush_hour               0
heavy_rain              0
temp_range              0
any_precipitation       0
dtype: int64

Borough distribution:
borough
Brooklyn         8084
Manhattan        4070
Queens           3792
Bronx            2952
Staten Island     817
Name: count, dtype: int64

Rush hour distribution:
rush_hour
0    13959
1     5756
Name: count, dtype: int64

Temp range distribution:
temp_range
cool           7409
comfortable    6046
cold           3780
hot            1680
freezing        800
Name: count, dtype: int64

Heavy rain distribution:
heavy_rain
0    18367
1     1348
Name: count, dtype: int64

Traffic volume stats:
count    19715.000000
mean       161.304772
std        239.954180
min          0.000000
25%         29.500000
50%         73.000000
75%        180.750000
max       1529.000000
Name: traffic_volume, dtype: float64

Date range covered:
  From: 2023-01-06 00:00:00
  To:   2023-12-10 23:00:00

In [44]:
# Road-level version
teammate_road_df = grouped_road[[
    'timestamp',
    'rain',
    'temperature',
    'snowfall',
    'traffic_volume',
    'traffic_index',
    'traffic_index_capped',
    'road_id',
    'borough',
    'rush_hour',
    'heavy_rain',
    'temp_range',
    'any_precipitation'
]].copy()

# Borough-level version
teammate_borough_df = grouped_borough[[
    'timestamp',
    'rain',
    'temperature',
    'snowfall',
    'traffic_volume',
    'traffic_index',
    'traffic_index_capped',
    'borough',
    'rush_hour',
    'heavy_rain',
    'temp_range',
    'any_precipitation'
]].copy()

print("Road-level shape:", teammate_road_df.shape)
print("Borough-level shape:", teammate_borough_df.shape)

teammate_road_df.head()

Road-level shape: (23665, 13)
Borough-level shape: (9414, 12)

,timestamp,rain,temperature,snowfall,traffic_volume,traffic_index,traffic_index_capped,road_id,borough,rush_hour,heavy_rain,temp_range,any_precipitation
0,2024-01-06,0.0,-3.2,0.0,14.50,1.257831,1.257831,METROPOLITAN AVENUE_WB,Brooklyn,0,0,freezing,0
1,2024-01-06,0.0,-3.2,0.0,2.75,0.531034,0.531034,9 AVENUE_SB,Manhattan,0,0,freezing,0
2,2024-01-06,0.0,-3.2,0.0,32.50,0.999146,0.999146,BROADWAY_NB,Queens,0,0,freezing,0
3,2024-01-06,0.0,-3.2,0.0,49.00,1.175217,1.175217,BROADWAY_SB,Queens,0,0,freezing,0
4,2024-01-06,0.0,-3.2,0.0,3.50,0.211765,0.211765,GRAND AVENUE_EB,Queens,0,0,freezing,0

In [45]:
# send cleaned feature tables to MySQL
teammate_road_df.to_sql(
    "road_level_features",
    con=engine,
    if_exists="replace",
    index=False
)

teammate_borough_df.to_sql(
    "borough_level_features",
    con=engine,
    if_exists="replace",
    index=False
)

print("road_level_features table written to MySQL")
print("borough_level_features table written to MySQL")

road_level_features table written to MySQL
borough_level_features table written to MySQL